version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - test-automation

  - package-ecosystem: npm
    directory: /apps/frontend
    schedule:
      interval: weekly
    labels:
      - dependencies
      - frontend

  - package-ecosystem: npm
    directory: /apps/mqtt-ingestion
    schedule:
      interval: weekly
    labels:
      - dependencies
      - mqtt

  - package-ecosystem: npm
    directory: /apps/device-simulator
    schedule:
      interval: weekly
    labels:
      - dependencies
      - mqtt

  - package-ecosystem: maven
    directory: /apps/backend
    schedule:
      interval: weekly
    labels:
      - dependencies
      - backend

  - package-ecosystem: docker
    directory: /apps/backend
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: /apps/frontend
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: /apps/mqtt-ingestion
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: /apps/device-simulator
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker