apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-metering-config
data:
  POSTGRES_DB: smart_metering
  MQTT_URL: mqtt://mqtt-broker:1883
  KAFKA_BROKERS: kafka:9092
  API_BASE_URL: http://backend:8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    listener 1883 0.0.0.0
    allow_anonymous true
    persistence false
    log_dest stdout
    log_type error
    log_type warning
    log_type notice
    connection_messages true
